mutation test_isfa_ganteng($param1: String, $param2: Int, $param3: Boolean) {
    test_isfa_ganteng(param1: $param1, param2: $param2, param3: $param3) {
        status
        data {
            name
            avatar
            phone
            address {
                zip
                province
            }
        }
    }
}